# Processing parameters
jetR: [0.5]

# For extra verbose output in some functions
debug_level: 0

process_observables: ['mass']
#process_observables: ['massPtRatio']
#process_observables: ['mass', 'zg', 'theta_g']
#process_observables: ['mass', 'massPtRatio', 'zg', 'theta_g']
#process_observables: ['massPtRatio']
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0


###############################################################################
# Rebinning and unfolding parameters/configurations for jet mass observables
mass:

  common_settings:
    xtitle: '#it{m}_{jet}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{m}_{jet}}'

  ############################################################################
  config_m:
    name: "mass"

  ############################################################################
  config_m_SD_zcut01:
    name: "groomed mass"
    SoftDrop:
      zcut: 0.1
      beta: 0

  ############################################################################
  #config_m_SD_zcut02:
  #  name: "groomed mass"
  #  SoftDrop:
  #    zcut: 0.2
  #    beta: 0

###############################################################################
# Rebinning and unfolding parameters/configurations for jet mass/pt observables
massPtRatio:

  common_settings:
    xtitle: '#it{m/pt}_{jet}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{m/pt}_{jet}}'

  ############################################################################
  config_mPR:
    name: "massPtRatio"

  ############################################################################
  config_mPR_SD_zcut01:
    name: "groomed massPtRatio"
    SoftDrop:
      zcut: 0.1
      beta: 0

###############################################################################
# Rebinning and unfolding parameters/configurations for jet groomed observables
zg:

  common_settings:
    xtitle: '#it{z}_{g}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{z}_{g}}'

  ############################################################################
  config_zg_zcut01:
    name: "zg"
    SoftDrop:
      zcut: 0.1
      beta: 0

  ############################################################################
  #config_zg_zcut02:
  #  name: "zg"
  #  SoftDrop:
  #    zcut: 0.2
  #    beta: 0

###############################################################################
theta_g:

  common_settings:
    xtitle: '#it{#theta}_{g}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{#theta}_{g}}'

  ############################################################################
  config_theta_g_zcut01:
    name: "theta_g"
    SoftDrop:
      zcut: 0.1
      beta: 0

  ############################################################################
  #config_theta_g_zcut02:
  #  name: "theta_g"
  #  SoftDrop:
  #    zcut: 0.2
  #    beta: 0
